### ISSUE TITLE
Bug: Snail not remebering docked location

### ISSUE THREAD

**Issue by Saijin-Naib** [pblottiere/snail#2]
Currently, Snail does not remember the panel to which it was docked, nor does it remember whether or not it was open/docked at the time of exiting QGIS.

Instead of restoring to its prior location and status, it instead is off/undocked by default, and when enabled, is positioned on the bottom of the left-most panel instead of where I had moved it prior.

**Comment by pblottiere** [comment]
Hi @Saijin-Naib,

It should be fixed in the new 1.0.1 version now.

Thanks for your feedback :+1:!
